version: '3'

services:

  back-end:
    build: ./product
    volumes:
      - ./product:/usr/src/app
    ports:
      - 5001:80

  front-end:
    image: php:apache
    volumes:
      - ./website:/var/www/html
    ports:
      - 5000:80
    depends_on:
      - back-end