version: '3'

services:

  back-end:
    build: ./back-end
    volumes:
      - ./back-end:/usr/src/app
    ports:
      - 5001:80

  front-end:
    image: php:apache
    volumes:
      - ./front-end:/var/www/html
    ports:
      - 5000:80
    depends_on:
      - back-end

  node:
    build: ./front-end/.Docker
    